// SPDX-FileCopyrightText: 2024–2026 Andy Curtis <contactandyc@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include <stdio.h>
#include <stdlib.h>

#include "a-memory-library/aml_pool.h"
#include "sql-parser-library/sql_ctx.h"
#include "sql-parser-library/sql_tokenizer.h"
#include "sql-parser-library/sql_query.h"

int main(int argc, char **argv) {
    // 1. Validate arguments
    if (argc < 2) {
        fprintf(stderr, "Usage: %s \"<SQL SELECT Statement>\"\n", argv[0]);
        return 1;
    }

    const char *raw_sql_string = argv[1];

    // 2. Initialize memory pool and SQL context
    aml_pool_t *pool = aml_pool_init(1024 * 1024); // 1MB pool
    if (!pool) {
        fprintf(stderr, "Failed to initialize memory pool.\n");
        return 1;
    }

    sql_ctx_t ctx = {0};
    ctx.pool = pool;

    // Register the standard functions, operators, and structural keywords
    register_ctx(&ctx);

    // 3. Tokenize the input string
    size_t token_count = 0;
    sql_token_t **tokens = sql_tokenize(&ctx, raw_sql_string, &token_count);

    if (!tokens || token_count == 0) {
        fprintf(stderr, "Failed to tokenize the input string.\n");
        sql_ctx_print_messages(&ctx);
        aml_pool_destroy(pool);
        return 1;
    }

    // 4. Parse into the high-level SELECT AST
    sql_select_t *ast = sql_parse_query(&ctx, tokens, token_count);

    if (ast) {
        // 5. Unparse the AST back into a normalized string
        char *normalized_sql = sql_query_to_string(&ctx, ast);

        printf("Original Input:        %s\n", raw_sql_string);
        printf("Normalized AST Output: %s\n", normalized_sql);
    } else {
        fprintf(stderr, "Failed to parse the SQL query.\n\n");

        // Print any syntax errors generated by the parser
        size_t nerr = 0;
        char **errs = sql_ctx_get_errors(&ctx, &nerr);
        for (size_t i = 0; i < nerr; i++) {
            fprintf(stderr, "Error: %s\n", errs[i]);
        }
    }

    // 6. Clean up (this frees the AST, tokens, and the normalized string all at once!)
    aml_pool_destroy(pool);
    return 0;
}
